Repository E-Edu/concept, pull requests merged in 2020-04, with the labels that each got.

#7 Created Custom 404 Error Page
  404.md
Labels: enhancement

#19 Merge draft-documents into concepts
  .gitignore
  documentation/dev/documentation.md
  documentation/dev/endpoints/concept.drawio
  documentation/dev/endpoints/concept.md
  documentation/dev/endpoints/img/concept-admin.svg
  documentation/dev/endpoints/img/concept-check-task.svg
  documentation/dev/endpoints/img/concept-create-task.svg
  documentation/dev/endpoints/img/concept-dashboard.svg
  documentation/dev/endpoints/img/concept-final-task.svg
  documentation/dev/endpoints/img/concept-login.svg
  documentation/dev/endpoints/img/concept-more-features.svg
  documentation/dev/endpoints/img/concept-task-types.svg
  documentation/dev/endpoints/img/concept-task.svg
  documentation/dev/endpoints/img/concept-teams.svg
  documentation/dev/endpoints/json/task.json
  documentation/dev/endpoints/json/ticket.json
  documentation/dev/endpoints/json/user.json
  documentation/dev/endpoints/markdown/errors.md
  documentation/dev/endpoints/swagger/microservice_com.yaml
  documentation/dev/endpoints/swagger/report.yaml
  documentation/dev/endpoints/swagger/task.yaml
  documentation/dev/endpoints/swagger/user.yaml
Labels: documentation, endpoints, enhancement

#42 Issue/13
  blog/technical/articles/teams.md
Labels: documentation

#55 Issue/54
  blog/technical/blog-technical.md
  changelog/meeting/changelog-meeting.md
Labels: bug, documentation
